### ISSUE TITLE
`status_abbrev': wrong number of arguments (given 3, expected 4) (ArgumentError)

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-gb#125]
https://github.com/metanorma/mn-samples-gb/pull/18/checks?check_run_id=631076346

```
/usr/local/bundle/gems/metanorma-iso-1.3.22/lib/isodoc/iso/metadata.rb:19:in `status_abbrev': wrong number of arguments (given 3, expected 4) (ArgumentError)
	from /usr/local/bundle/gems/metanorma-gb-1.3.21/lib/asciidoctor/gb/front.rb:220:in `id_stage_prefix'
	from /usr/local/bundle/gems/metanorma-gb-1.3.21/lib/asciidoctor/gb/front.rb:199:in `iso_id'
	from /usr/local/bundle/gems/metanorma-iso-1.3.22/lib/asciidoctor/iso/front.rb:48:in `metadata_id'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/front.rb:150:in `metadata'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/base.rb:193:in `block in front'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/base.rb:192:in `front'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/base.rb:169:in `block in makexml1'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `new'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `with'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/utils.rb:137:in `noko'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/base.rb:169:in `makexml1'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/base.rb:176:in `makexml'
	from /usr/local/bundle/gems/metanorma-gb-1.3.21/lib/asciidoctor/gb/converter.rb:25:in `makexml'
	from /usr/local/bundle/gems/metanorma-gb-1.3.21/lib/asciidoctor/gb/converter.rb:63:in `document'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.24/lib/asciidoctor/standoc/utils.rb:116:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120:in `convert'
	from /usr/local/bundle/gems/metanorma-1.0.3/lib/metanorma/input/asciidoc.rb:10:in `process'
	from /usr/local/bundle/gems/metanorma-gb-1.3.21/lib/metanorma/gb/processor.rb:26:in `input_to_isodoc'
	from /usr/local/bundle/gems/metanorma-1.0.3/lib/metanorma/compile.rb:113:in `process_input'
	from /usr/local/bundle/gems/metanorma-1.0.3/lib/metanorma/compile.rb:17:in `compile'
	from /usr/local/bundle/bundler/gems/metanorma-cli-69061571f468/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	from /usr/local/bundle/bundler/gems/metanorma-cli-69061571f468/lib/metanorma/cli/compiler.rb:29:in `compile'
	from /usr/local/bundle/bundler/gems/metanorma-cli-69061571f468/lib/metanorma/cli/compiler.rb:33:in `compile'
	from /usr/local/bundle/bundler/gems/metanorma-cli-69061571f468/lib/metanorma/cli/command.rb:35:in `compile'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/bundler/gems/metanorma-cli-69061571f468/lib/metanorma/cli.rb:60:in `start'
	from /usr/local/bundle/bundler/gems/metanorma-cli-69061571f468/exe/metanorma:20:in `<top (required)>'
	from /usr/local/bundle/bin/metanorma:23:in `load'
	from /usr/local/bundle/bin/metanorma:23:in `<main>'
make: *** [sources/rice.gb.en.xml] Error 1

```

**Comment by opoudjis** [comment]
I'll take care of this; this is the kind of thing that gets resolved on release
